name       : mate-utils
version    : 1.20.1
release    : 10
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-utils-1.20.1.tar.xz : 6a1e0bba9c117f8ce81bb271d2182006524250fe9e31f2fc904f6403453020cf
license    :
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
