name       : mate-utils
version    : 1.22.0
release    : 13
source     :
    - https://github.com/mate-desktop//mate-utils/archive/v1.22.0.tar.gz : a6e39532517d2d0b001bb1e852c9d9a3fd38b8752c21b7b11c3e68599cbe8097
license    :
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - itstool
    - mate-common
    - yelp-devel
    - yelp-tools
setup      : |
    %autogen --disable-static \
        --disable-debug \
        --disable-maintainer-flags \
        --enable-gtk-doc \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
