name       : mate-utils
version    : 1.18.2
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-utils-1.18.2.tar.xz : bbd80f772d9f4dd379794105fd7a4f5452c71ff3e634a06f0af245875b492373
license    :
    - GPL-2.0
    - GFDL-1.1
    - LGPL-2.1
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
