name       : mate-utils
version    : 1.27.0
release    : 25
source     :
    - https://github.com/mate-desktop/mate-utils/releases/download/v1.27.0/mate-utils-1.27.0.tar.xz : 1ace72641eac1fcc814f09aab5f10fbd25a67bfb1c473c2118aea252631dfcb0
license    :
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(sm)
    - pkgconfig(udisks2)
    - pkgconfig(xext)
    - itstool
setup      : |
    export PYTHON=/usr/bin/python3
    %configure --disable-static \
        --disable-debug \
        --disable-maintainer-flags \
        --enable-gtk-doc \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
