name       : mate-utils
version    : 1.20.0
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-utils-1.20.0.tar.xz : f4c2ca4fe533538976412c0fab282a1c8e61f4987bc920d7a452b1131f9a4681
license    :
    - GPL-2.0
    - GFDL-1.1
    - LGPL-2.1
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
