name       : mate-utils
version    : 1.18.0
release    : 3
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-utils-1.18.0.tar.xz : ed482f651e8379b9963f93399d8590df4e28ea3cc8dc8c0603c1fac7c5fa10d1
license    :
    - GPL-2.0
    - GFDL-1.1
    - LGPL-2.1
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
