name       : mate-utils
version    : 1.24.0
release    : 20
source     :
    - https://github.com/mate-desktop/mate-utils/archive/v1.24.0.tar.gz : 139ba40ca12bac146e22f00c502bb4e742f8eeb2df51eafc8833bfa761ec65d1
license    :
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(sm)
    - pkgconfig(udisks2)
    - pkgconfig(xext)
    - itstool
    - mate-common
    - yelp-devel
    - yelp-tools
setup      : |
    export PYTHON=/usr/bin/python3
    %autogen --disable-static \
        --disable-debug \
        --disable-maintainer-flags \
        --enable-gtk-doc \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
