name       : mate-utils
version    : 1.22.2
release    : 17
source     :
    - https://github.com/mate-desktop/mate-utils/archive/v1.22.2.tar.gz : 4172636d1744e814432762afcd4b9b66743aa84f342fe5ee16d081afbf1bf72e
license    :
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(inkdbus)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - itstool
    - mate-common
    - yelp-devel
    - yelp-tools
setup      : |
    export PYTHON=/usr/bin/python3
    %autogen --disable-static \
        --disable-debug \
        --disable-maintainer-flags \
        --enable-gtk-doc \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
