name       : mate-utils
version    : 1.14.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-utils-1.14.1.tar.xz : 6632c1fe72187ed1d77ee8e55cf70885b2611c086b606b92010d2a4f193ab4dd
license    :
    - GPL-2.0
    - GFDL-1.1
    - LGPL-2.1
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
