name       : mate-utils
version    : 1.20.2
release    : 11
source     :
    - https://github.com/mate-desktop/mate-utils/archive/v1.20.2.tar.gz : da474b08efb0b478c12712af93e883d6d3ad5361377aa6d3a296bf8dc1d4f61d
license    :
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - itstool
    - mate-common
    - yelp-devel
    - yelp-tools
setup      : |
    %autogen --disable-static --disable-debug --enable-ipv6 --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
