name       : mate-utils
version    : 1.26.0
release    : 22
source     :
    - https://github.com/mate-desktop/mate-utils/releases/download/v1.26.0/mate-utils-1.26.0.tar.xz : 7ca56ab242e8efaa64f93ffb84f6e4bf8d4d0df01e20b3b6ef8956ce3192782e
license    :
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : Utilities for the MATE Desktop
description: |
    Utilities for the MATE Desktop such as a screenshot tool
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(sm)
    - pkgconfig(udisks2)
    - pkgconfig(xext)
    - itstool
setup      : |
    export PYTHON=/usr/bin/python3
    %configure --disable-static \
        --disable-debug \
        --disable-maintainer-flags \
        --enable-gtk-doc \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
